### ISSUE TITLE
Convert the amount types to appropriate sizes

### ISSUE THREAD

**Issue by matrulda** [matrulda/gimme-food#2]
After sum up, convert liter and gram to appropriate sizes. 

For example: 0.03 l --> 2 msk

**Comment by sarek928** [comment]
It would be a nice feature to convert volume to weight also. For example: 2 dl water >> 200 g water

**Comment by matrulda** [comment]
@sarek928 I made a separate issue for your excellent suggestion. As a fist step I'm going to do the conversion within the same unit of measurement.
