### ISSUE TITLE
Give recipe based on ingredients

### ISSUE THREAD

**Issue by sarek928** [matrulda/gimme-food#3]
It would be a nice feature, if you could give ingredients you have at home as a input and receive a recipe based on that.

For example: input: tomatoes, eggplant, cucumber, garlic
output: gazpacho recipe

**Comment by matrulda** [comment]
Great suggestion! Will definitely be included in later versions.

**Comment by matrulda** [comment]
This is fixed now @sarek928 ! Thanks for the suggestion. I'm going to make a production release soon with an updated README explaining how it works, but feel free to try it before that.
